import type { AroundYouLanguage, PassengerLocationStatus } from "./around-you-types";

export const aroundYouCopy = {
  en: {
    eyebrow: "Near you now",
    title: "Around You",
    homeDescription: "A local story is ready when you are.",
    open: "Explore nearby",
    back: "Back to Home",
    featured: "Right around you",
    nearby: "Nearby",
    browse: "Explore Utah",
    browseDescription: "A small local guide for the places STREEX calls home.",
    allPlaces: "All places",
    liveContext: "Back to live context",
    localStory: "Local story",
    funFact: "Good to know",
    elevation: "Elevation",
    noNearby: "Nothing nearby just yet",
    imageUnavailable: "Local place guide",
    distanceAway: "away",
    categories: {
      city: "City",
      culture: "Culture",
      history: "History",
      nature: "Nature",
      mountain: "Mountains",
      sports: "Sports",
      transportation: "On the move",
      university: "University",
      viewpoint: "Viewpoint",
    },
    noMatch: "Keep moving — a local story will appear when one is nearby.",
    fallbackTitle: "Explore nearby",
    fallbackDescription: "Location context is unavailable, but local discovery is still here.",
    testModeEyebrow: "PRIVATE OWNER TOOL",
    testModeLabel: "Around You test location",
    testModeDescription: "Use the tablet GPS or simulate a Utah location. This panel is not shown to passengers.",
    testUseLiveGps: "Use live tablet GPS",
    status: {
      idle: "Local discovery is ready when enabled.",
      requesting: "Finding where the tablet is…",
      ready: "Live local context",
      degraded: "Using the last reliable location",
      stale: "Waiting for a fresh GPS signal",
      denied: "Location permission is off",
      unavailable: "GPS is temporarily unavailable",
      unsupported: "Location is not supported in this browser",
    } satisfies Record<PassengerLocationStatus, string>,
  },
  es: {
    eyebrow: "Cerca de ti ahora",
    title: "A tu alrededor",
    homeDescription: "Una historia local está lista cuando tú lo estés.",
    open: "Explorar cerca",
    back: "Volver a Inicio",
    featured: "Justo a tu alrededor",
    nearby: "Cerca de aquí",
    browse: "Explora Utah",
    browseDescription: "Una pequeña guía local de los lugares que Streex llama hogar.",
    allPlaces: "Todos los lugares",
    liveContext: "Volver al contexto en vivo",
    localStory: "Historia local",
    funFact: "Dato para recordar",
    elevation: "Altitud",
    noNearby: "Aún no hay lugares cerca",
    imageUnavailable: "Guía local de lugares",
    distanceAway: "de distancia",
    categories: {
      city: "Ciudad",
      culture: "Cultura",
      history: "Historia",
      nature: "Naturaleza",
      mountain: "Montaña",
      sports: "Deportes",
      transportation: "En ruta",
      university: "Universidad",
      viewpoint: "Mirador",
    },
    noMatch: "Sigue avanzando: aparecerá una historia local cuando haya una cerca.",
    fallbackTitle: "Explora cerca",
    fallbackDescription:
      "El contexto de ubicación no está disponible, pero aún puedes descubrir Utah.",
    testModeEyebrow: "HERRAMIENTA PRIVADA",
    testModeLabel: "Ubicación de prueba de A tu alrededor",
    testModeDescription: "Usa el GPS de la tablet o simula una ubicación de Utah. Este panel no se muestra a pasajeros.",
    testUseLiveGps: "Usar GPS real de la tablet",
    status: {
      idle: "El descubrimiento local estará listo cuando se active.",
      requesting: "Buscando la ubicación de la tablet…",
      ready: "Contexto local en vivo",
      degraded: "Usando la última ubicación confiable",
      stale: "Esperando una señal GPS reciente",
      denied: "El permiso de ubicación está desactivado",
      unavailable: "El GPS no está disponible temporalmente",
      unsupported: "Este navegador no admite ubicación",
    } satisfies Record<PassengerLocationStatus, string>,
  },
} as const satisfies Record<AroundYouLanguage, unknown>;
