import type { AroundYouPlace } from "./around-you-types";

// Curated local catalog. Coordinates and facts are verified against the linked public/official
// sources before inclusion. Priority follows the documented 0–100 landmark scale in specs.md.
export const AROUND_YOU_SEED_PLACES: AroundYouPlace[] = [
  {
    id: "salt-lake-valley",
    enabled: true,
    latitude: 40.746,
    longitude: -111.891,
    category: "city",
    contextType: "region",
    priority: 42,
    triggerRadiusMeters: 28_000,
    discoveryRadiusMeters: 38_000,
    imageSrc: "/images/passenger/around-you/salt-lake-valley.webp",
    title: { en: "Salt Lake Valley", es: "Valle de Salt Lake" },
    description: {
      en: "A wide urban valley framed by the Wasatch Mountains to the east and the Great Salt Lake to the west.",
      es: "Un amplio valle urbano enmarcado por las montañas Wasatch al este y el Gran Lago Salado al oeste.",
    },
    funFact: {
      en: "The mountains you see from the valley rise quickly from the city floor.",
      es: "Las montañas que se ven desde el valle se elevan rápidamente desde la ciudad.",
    },
    sourceUrl: "https://www.visitsaltlake.com/",
    tags: ["salt-lake-city", "region", "wasatch"],
  },
  {
    id: "wasatch-back",
    enabled: true,
    latitude: 40.693,
    longitude: -111.528,
    category: "mountain",
    contextType: "region",
    priority: 41,
    triggerRadiusMeters: 30_000,
    discoveryRadiusMeters: 42_000,
    imageSrc: "/images/passenger/around-you/wasatch-back.webp",
    title: { en: "The Wasatch Back", es: "El Wasatch Back" },
    description: {
      en: "The mountain side of northern Utah, where the road climbs toward Park City, reservoirs and alpine trails.",
      es: "El lado montañoso del norte de Utah, donde la ruta asciende hacia Park City, embalses y senderos alpinos.",
    },
    sourceUrl: "https://www.visitparkcity.com/",
    tags: ["park-city", "region", "mountain"],
  },
  {
    id: "downtown-salt-lake-city",
    enabled: true,
    latitude: 40.7608,
    longitude: -111.891,
    category: "city",
    contextType: "region",
    priority: 56,
    triggerRadiusMeters: 4_500,
    discoveryRadiusMeters: 9_000,
    imageSrc: "/images/passenger/around-you/downtown-slc.jpg",
    title: { en: "Downtown Salt Lake City", es: "Centro de Salt Lake City" },
    description: {
      en: "Utah's capital city sits between the Wasatch Mountains and the Great Salt Lake.",
      es: "La capital de Utah se encuentra entre las montañas Wasatch y el Gran Lago Salado.",
    },
    funFact: {
      en: "The city grid is organized around Temple Square.",
      es: "La cuadrícula de la ciudad se organiza alrededor de Temple Square.",
    },
    sourceUrl: "https://www.slc.gov/",
    tags: ["salt-lake-city", "downtown"],
  },
  {
    id: "utah-state-capitol",
    enabled: true,
    latitude: 40.7774,
    longitude: -111.8882,
    category: "history",
    contextType: "landmark",
    priority: 96,
    triggerRadiusMeters: 1_500,
    discoveryRadiusMeters: 5_500,
    title: { en: "Utah State Capitol", es: "Capitolio del Estado de Utah" },
    description: {
      en: "The Capitol overlooks Salt Lake City from the north end of State Street.",
      es: "El Capitolio domina Salt Lake City desde el extremo norte de State Street.",
    },
    funFact: {
      en: "Its hilltop setting gives it a commanding view of the valley.",
      es: "Su ubicación elevada ofrece una vista dominante del valle.",
    },
    sourceUrl: "https://www.slc.gov/district3/tour-district-3/utah-state-capitol/",
    tags: ["salt-lake-city", "history"],
  },
  {
    id: "temple-square",
    enabled: true,
    latitude: 40.7701,
    longitude: -111.8928,
    category: "culture",
    contextType: "landmark",
    priority: 94,
    triggerRadiusMeters: 1_700,
    discoveryRadiusMeters: 5_000,
    title: { en: "Temple Square", es: "Temple Square" },
    description: {
      en: "A landmark at the center of Salt Lake City's historic downtown.",
      es: "Un ícono en el corazón del centro histórico de Salt Lake City.",
    },
    funFact: {
      en: "It is Utah's most-visited attraction.",
      es: "Es la atracción más visitada de Utah.",
    },
    sourceUrl: "https://travel.utah.gov/",
    tags: ["salt-lake-city", "culture"],
  },
  {
    id: "city-creek-canyon",
    enabled: true,
    latitude: 40.783,
    longitude: -111.879,
    category: "nature",
    contextType: "landmark",
    priority: 82,
    triggerRadiusMeters: 2_500,
    discoveryRadiusMeters: 6_500,
    title: { en: "City Creek Canyon", es: "Cañón City Creek" },
    description: {
      en: "A protected watershed and nature preserve right beside the capital city.",
      es: "Una cuenca protegida y reserva natural junto a la capital.",
    },
    funFact: {
      en: "City Creek was one of the first water sources used by the 1847 settlers.",
      es: "City Creek fue una de las primeras fuentes de agua usadas por los colonos de 1847.",
    },
    sourceUrl: "https://www.slc.gov/utilities/city-creek-canyon/",
    tags: ["salt-lake-city", "nature"],
  },
  {
    id: "liberty-park",
    enabled: true,
    latitude: 40.7468,
    longitude: -111.8757,
    category: "culture",
    contextType: "landmark",
    priority: 70,
    triggerRadiusMeters: 1_800,
    discoveryRadiusMeters: 4_800,
    title: { en: "Liberty Park", es: "Parque Liberty" },
    description: {
      en: "One of Salt Lake City's classic public parks, just south of downtown.",
      es: "Uno de los parques públicos clásicos de Salt Lake City, al sur del centro.",
    },
    sourceUrl: "https://www.slc.gov/parks/",
    tags: ["salt-lake-city", "park"],
  },
  {
    id: "university-of-utah",
    enabled: true,
    latitude: 40.7649,
    longitude: -111.8479,
    category: "university",
    contextType: "landmark",
    priority: 84,
    triggerRadiusMeters: 2_400,
    discoveryRadiusMeters: 6_000,
    title: { en: "University of Utah", es: "Universidad de Utah" },
    description: {
      en: "A major research university set against the foothills above Salt Lake City.",
      es: "Una importante universidad de investigación junto a las estribaciones sobre Salt Lake City.",
    },
    sourceUrl: "https://www.utah.edu/",
    tags: ["salt-lake-city", "university"],
  },
  {
    id: "red-butte-garden",
    enabled: true,
    latitude: 40.7696,
    longitude: -111.8262,
    category: "nature",
    contextType: "landmark",
    priority: 80,
    triggerRadiusMeters: 2_000,
    discoveryRadiusMeters: 6_000,
    title: { en: "Red Butte Garden", es: "Jardín Red Butte" },
    description: {
      en: "A botanical garden and arboretum in the foothills above the city.",
      es: "Un jardín botánico y arboreto en las estribaciones sobre la ciudad.",
    },
    sourceUrl: "https://www.redbuttegarden.org/",
    tags: ["salt-lake-city", "nature"],
  },
  {
    id: "this-is-the-place",
    enabled: true,
    latitude: 40.7555,
    longitude: -111.8218,
    category: "history",
    contextType: "landmark",
    priority: 86,
    triggerRadiusMeters: 2_200,
    discoveryRadiusMeters: 5_500,
    title: { en: "This Is The Place Heritage Park", es: "Parque Patrimonial This Is The Place" },
    description: {
      en: "A landmark park preserving stories from Utah's pioneer era.",
      es: "Un parque emblemático que conserva historias de la era pionera de Utah.",
    },
    sourceUrl: "https://thisistheplace.org/",
    tags: ["salt-lake-city", "history"],
  },
  {
    id: "salt-lake-city-airport",
    enabled: true,
    latitude: 40.7899,
    longitude: -111.9791,
    category: "transportation",
    contextType: "landmark",
    priority: 88,
    triggerRadiusMeters: 3_500,
    discoveryRadiusMeters: 10_000,
    title: {
      en: "Salt Lake City International Airport",
      es: "Aeropuerto Internacional de Salt Lake City",
    },
    description: {
      en: "A major gateway to Utah and the Mountain West.",
      es: "Una importante puerta de entrada a Utah y al oeste montañoso.",
    },
    sourceUrl: "https://slcairport.com/about-the-airport/airport-overview/",
    tags: ["airport", "transportation"],
  },
  {
    id: "great-salt-lake",
    enabled: true,
    latitude: 40.7347,
    longitude: -112.2128,
    category: "nature",
    contextType: "landmark",
    priority: 92,
    triggerRadiusMeters: 7_500,
    discoveryRadiusMeters: 18_000,
    imageSrc: "/images/passenger/around-you/great-salt-lake.jpg",
    title: { en: "Great Salt Lake", es: "Gran Lago Salado" },
    description: {
      en: "A terminal lake with no outlet, where water evaporates and minerals remain.",
      es: "Un lago terminal sin salida, donde el agua se evapora y los minerales permanecen.",
    },
    sourceUrl: "https://stateparks.utah.gov/parks/great-salt-lake/",
    tags: ["nature", "lake"],
  },
  {
    id: "parleys-canyon",
    enabled: true,
    latitude: 40.7317,
    longitude: -111.7839,
    category: "mountain",
    contextType: "region",
    priority: 72,
    triggerRadiusMeters: 5_000,
    discoveryRadiusMeters: 11_000,
    elevationFeet: 5_600,
    title: { en: "Parley's Canyon", es: "Cañón Parley" },
    description: {
      en: "A historic route connecting the Salt Lake Valley with the Wasatch Back.",
      es: "Una ruta histórica que conecta el valle de Salt Lake con el Wasatch Back.",
    },
    sourceUrl: "https://www.slc.gov/parks/parks-division/parleys-historic-nature-park/",
    tags: ["mountain", "park-city"],
  },
  {
    id: "lagoon-amusement-park",
    enabled: true,
    latitude: 40.9847,
    longitude: -111.895,
    category: "culture",
    contextType: "landmark",
    priority: 84,
    triggerRadiusMeters: 2_200,
    discoveryRadiusMeters: 7_000,
    title: { en: "Lagoon", es: "Lagoon" },
    description: {
      en: "A longtime Utah amusement park located in Farmington.",
      es: "Un histórico parque de diversiones de Utah ubicado en Farmington.",
    },
    sourceUrl: "https://www.lagoonpark.com/contact-us/",
    tags: ["farmington", "culture"],
  },
  {
    id: "ogden",
    enabled: true,
    latitude: 41.223,
    longitude: -111.9738,
    category: "history",
    contextType: "region",
    priority: 60,
    triggerRadiusMeters: 6_500,
    discoveryRadiusMeters: 13_000,
    title: { en: "Ogden", es: "Ogden" },
    description: {
      en: "Once known as Junction City, Ogden grew around its railroad connections.",
      es: "Conocida como Junction City, Ogden creció alrededor de sus conexiones ferroviarias.",
    },
    sourceUrl: "https://council.ogdencity.com/560/About-Ogden",
    tags: ["ogden", "history"],
  },
  {
    id: "antelope-island",
    enabled: true,
    latitude: 41.0577,
    longitude: -112.2358,
    category: "nature",
    contextType: "landmark",
    priority: 91,
    triggerRadiusMeters: 8_000,
    discoveryRadiusMeters: 20_000,
    title: { en: "Antelope Island", es: "Isla Antelope" },
    description: {
      en: "A Great Salt Lake island known for wide-open views and wildlife.",
      es: "Una isla del Gran Lago Salado conocida por sus amplias vistas y vida silvestre.",
    },
    sourceUrl: "https://stateparks.utah.gov/parks/antelope-island/",
    tags: ["nature", "great-salt-lake"],
  },
  {
    id: "park-city",
    enabled: true,
    latitude: 40.6461,
    longitude: -111.498,
    category: "city",
    contextType: "region",
    priority: 68,
    triggerRadiusMeters: 6_000,
    discoveryRadiusMeters: 12_000,
    imageSrc: "/images/passenger/around-you/park-city.jpg",
    elevationFeet: 7_000,
    title: { en: "Park City", es: "Park City" },
    description: {
      en: "A historic silver-mining town turned year-round mountain and arts destination.",
      es: "Una histórica ciudad minera de plata convertida en destino de montaña y artes durante todo el año.",
    },
    sourceUrl: "https://www.visitparkcity.com/things-to-do/museums-history/park-city-history/",
    tags: ["park-city", "mountain"],
  },
  {
    id: "historic-main-street",
    enabled: true,
    latitude: 40.646,
    longitude: -111.4981,
    category: "culture",
    contextType: "landmark",
    priority: 88,
    triggerRadiusMeters: 1_700,
    discoveryRadiusMeters: 5_000,
    elevationFeet: 7_000,
    title: { en: "Historic Main Street", es: "Historic Main Street" },
    description: {
      en: "Park City's walkable heart, with independent shops, galleries and restaurants.",
      es: "El corazón caminable de Park City, con tiendas independientes, galerías y restaurantes.",
    },
    sourceUrl: "https://www.visitparkcity.com/about-park-city/frequently-asked-questions/",
    tags: ["park-city", "culture"],
  },
  {
    id: "utah-olympic-park",
    enabled: true,
    latitude: 40.7114,
    longitude: -111.561,
    category: "sports",
    contextType: "landmark",
    priority: 95,
    triggerRadiusMeters: 2_500,
    discoveryRadiusMeters: 9_000,
    imageSrc: "/images/passenger/around-you/utah-olympic-park.jpg",
    elevationFeet: 6_800,
    title: { en: "Utah Olympic Park", es: "Parque Olímpico de Utah" },
    description: {
      en: "A 2002 Winter Games venue that keeps Utah's Olympic sport legacy moving.",
      es: "Una sede de los Juegos de Invierno de 2002 que mantiene vivo el legado olímpico de Utah.",
    },
    funFact: {
      en: "Its Nordic jumps are visible as you approach Park City from I-80.",
      es: "Sus saltos nórdicos son visibles al acercarse a Park City desde la I-80.",
    },
    sourceUrl: "https://www.visitparkcity.com/things-to-do/utah-olympic-park/",
    tags: ["park-city", "sports"],
  },
  {
    id: "kimball-junction",
    enabled: true,
    latitude: 40.7216,
    longitude: -111.543,
    category: "culture",
    contextType: "region",
    priority: 62,
    triggerRadiusMeters: 3_500,
    discoveryRadiusMeters: 8_000,
    elevationFeet: 6_400,
    title: { en: "Kimball Junction", es: "Kimball Junction" },
    description: {
      en: "A Park City gateway with easy access to the Olympic Park and mountain communities.",
      es: "Una puerta de entrada a Park City con fácil acceso al Parque Olímpico y comunidades de montaña.",
    },
    sourceUrl:
      "https://www.visitparkcity.com/listing/kimball-junction-visitor-information-center/17460/",
    tags: ["park-city", "culture"],
  },
  {
    id: "deer-valley",
    enabled: true,
    latitude: 40.6379,
    longitude: -111.4783,
    category: "mountain",
    contextType: "landmark",
    priority: 89,
    triggerRadiusMeters: 3_000,
    discoveryRadiusMeters: 8_500,
    elevationFeet: 7_200,
    title: { en: "Deer Valley", es: "Deer Valley" },
    description: {
      en: "One of Park City's renowned mountain resort areas, set above historic town.",
      es: "Una de las reconocidas zonas de montaña de Park City, sobre la ciudad histórica.",
    },
    sourceUrl: "https://www.visitparkcity.com/",
    tags: ["park-city", "mountain"],
  },
  {
    id: "natural-history-museum-utah",
    enabled: true,
    latitude: 40.7658,
    longitude: -111.8235,
    category: "culture",
    contextType: "landmark",
    priority: 83,
    triggerRadiusMeters: 2_200,
    discoveryRadiusMeters: 6_000,
    imageSrc: "/images/passenger/around-you/salt-lake-valley.webp",
    title: { en: "Natural History Museum of Utah", es: "Museo de Historia Natural de Utah" },
    description: {
      en: "A hillside museum where Utah's fossils, landscapes and cultures are explored through hands-on exhibits.",
      es: "Un museo en la ladera que explora fósiles, paisajes y culturas de Utah con exhibiciones interactivas.",
    },
    sourceUrl: "https://nhmu.utah.edu/",
    tags: ["salt-lake-city", "museum", "culture"],
  },
  {
    id: "ensign-peak",
    enabled: true,
    latitude: 40.7924,
    longitude: -111.8915,
    category: "viewpoint",
    contextType: "landmark",
    priority: 76,
    triggerRadiusMeters: 2_000,
    discoveryRadiusMeters: 5_500,
    imageSrc: "/images/passenger/around-you/salt-lake-valley.webp",
    title: { en: "Ensign Peak", es: "Ensign Peak" },
    description: {
      en: "A foothill overlook north of downtown with a classic view across the Salt Lake Valley.",
      es: "Un mirador en las estribaciones al norte del centro con una vista clásica del valle de Salt Lake.",
    },
    sourceUrl: "https://www.slc.gov/parks/parks-division/ensign-peak-nature-park/",
    tags: ["salt-lake-city", "viewpoint", "nature"],
  },
  {
    id: "tracy-aviary",
    enabled: true,
    latitude: 40.7447,
    longitude: -111.8729,
    category: "nature",
    contextType: "landmark",
    priority: 72,
    triggerRadiusMeters: 1_900,
    discoveryRadiusMeters: 5_000,
    imageSrc: "/images/passenger/around-you/salt-lake-valley.webp",
    title: { en: "Tracy Aviary", es: "Aviario Tracy" },
    description: {
      en: "A century-old bird conservation center inside Liberty Park.",
      es: "Un centro de conservación de aves con más de un siglo de historia dentro de Liberty Park.",
    },
    sourceUrl: "https://tracyaviary.org/",
    tags: ["salt-lake-city", "nature", "liberty-park"],
  },
  {
    id: "hogle-zoo",
    enabled: true,
    latitude: 40.7516,
    longitude: -111.8217,
    category: "nature",
    contextType: "landmark",
    priority: 74,
    triggerRadiusMeters: 2_100,
    discoveryRadiusMeters: 5_500,
    imageSrc: "/images/passenger/around-you/salt-lake-valley.webp",
    title: { en: "Utah's Hogle Zoo", es: "Zoológico Hogle de Utah" },
    description: {
      en: "A wildlife and conservation destination at the mouth of Emigration Canyon.",
      es: "Un destino de vida silvestre y conservación en la entrada de Emigration Canyon.",
    },
    sourceUrl: "https://www.hoglezoo.org/",
    tags: ["salt-lake-city", "nature", "family"],
  },
  {
    id: "the-gateway",
    enabled: true,
    latitude: 40.7681,
    longitude: -111.9036,
    category: "culture",
    contextType: "landmark",
    priority: 69,
    triggerRadiusMeters: 1_800,
    discoveryRadiusMeters: 4_800,
    imageSrc: "/images/passenger/around-you/downtown-slc.jpg",
    title: { en: "The Gateway", es: "The Gateway" },
    description: {
      en: "A downtown district near the old rail yards with dining, entertainment and open gathering space.",
      es: "Un distrito del centro cerca de los antiguos patios ferroviarios con restaurantes, entretenimiento y espacios abiertos.",
    },
    sourceUrl: "https://atthegateway.com/",
    tags: ["salt-lake-city", "downtown", "culture"],
  },
  {
    id: "gilgal-sculpture-garden",
    enabled: true,
    latitude: 40.7521,
    longitude: -111.8747,
    category: "culture",
    contextType: "landmark",
    priority: 68,
    triggerRadiusMeters: 1_500,
    discoveryRadiusMeters: 4_000,
    imageSrc: "/images/passenger/around-you/salt-lake-valley.webp",
    title: { en: "Gilgal Sculpture Garden", es: "Jardín de Esculturas Gilgal" },
    description: {
      en: "A compact, surprising sculpture garden tucked into a residential Salt Lake City block.",
      es: "Un pequeño y sorprendente jardín de esculturas escondido en una manzana residencial de Salt Lake City.",
    },
    sourceUrl: "https://www.slc.gov/parks/parks-division/gilgal-sculpture-garden/",
    tags: ["salt-lake-city", "art", "culture"],
  },
  {
    id: "swaner-preserve",
    enabled: true,
    latitude: 40.7252,
    longitude: -111.5362,
    category: "nature",
    contextType: "landmark",
    priority: 74,
    triggerRadiusMeters: 2_400,
    discoveryRadiusMeters: 6_000,
    imageSrc: "/images/passenger/around-you/wasatch-back.webp",
    title: { en: "Swaner Preserve", es: "Reserva Swaner" },
    description: {
      en: "A protected wetland and nature preserve at Park City's Kimball Junction gateway.",
      es: "Un humedal protegido y reserva natural en la puerta de entrada Kimball Junction de Park City.",
    },
    sourceUrl: "https://swanerecocenter.org/",
    tags: ["park-city", "nature", "kimball-junction"],
  },
  {
    id: "mcpollin-barn",
    enabled: true,
    latitude: 40.7015,
    longitude: -111.5419,
    category: "history",
    contextType: "landmark",
    priority: 70,
    triggerRadiusMeters: 1_600,
    discoveryRadiusMeters: 4_500,
    imageSrc: "/images/passenger/around-you/wasatch-back.webp",
    title: { en: "McPolin Barn", es: "Granero McPolin" },
    description: {
      en: "A familiar red barn and historic farmstead along the McLeod Creek Trail in Park City.",
      es: "Un reconocido granero rojo y granja histórica junto al sendero McLeod Creek en Park City.",
    },
    sourceUrl: "https://www.parkcity.org/departments/trails-open-space/historic-mcpolin-barn",
    tags: ["park-city", "history", "trail"],
  },
  {
    id: "jordanelle-state-park",
    enabled: true,
    latitude: 40.6426,
    longitude: -111.4202,
    category: "nature",
    contextType: "landmark",
    priority: 79,
    triggerRadiusMeters: 5_500,
    discoveryRadiusMeters: 13_000,
    imageSrc: "/images/passenger/around-you/wasatch-back.webp",
    title: { en: "Jordanelle State Park", es: "Parque Estatal Jordanelle" },
    description: {
      en: "A reservoir and year-round recreation area just east of Park City.",
      es: "Un embalse y área recreativa durante todo el año al este de Park City.",
    },
    sourceUrl: "https://stateparks.utah.gov/parks/jordanelle/",
    tags: ["park-city", "nature", "water"],
  },
  {
    id: "guardsman-pass",
    enabled: true,
    latitude: 40.6104,
    longitude: -111.5305,
    category: "viewpoint",
    contextType: "landmark",
    priority: 81,
    triggerRadiusMeters: 4_500,
    discoveryRadiusMeters: 12_000,
    elevationFeet: 9_700,
    imageSrc: "/images/passenger/around-you/wasatch-back.webp",
    title: { en: "Guardsman Pass", es: "Paso Guardsman" },
    description: {
      en: "A high mountain pass with sweeping Wasatch views between the Park City area and Big Cottonwood Canyon.",
      es: "Un paso de alta montaña con amplias vistas de Wasatch entre el área de Park City y Big Cottonwood Canyon.",
    },
    sourceUrl: "https://www.fs.usda.gov/recarea/uwcnf/recarea/?recid=8982",
    tags: ["park-city", "viewpoint", "mountain"],
  },
  {
    id: "egyptian-theatre",
    enabled: true,
    latitude: 40.6464,
    longitude: -111.4978,
    category: "culture",
    contextType: "landmark",
    priority: 75,
    triggerRadiusMeters: 1_100,
    discoveryRadiusMeters: 3_600,
    imageSrc: "/images/passenger/around-you/park-city.jpg",
    title: { en: "Egyptian Theatre", es: "Teatro Egyptian" },
    description: {
      en: "A historic Main Street theatre and a familiar home for live performances in Park City.",
      es: "Un histórico teatro de Main Street y un reconocido hogar de espectáculos en vivo en Park City.",
    },
    sourceUrl: "https://www.egyptiantheatrecompany.org/",
    tags: ["park-city", "culture", "main-street"],
  },
];
