import type { AroundYouPlace } from "./around-you-types";

// First-pass seed only. Facts and locations are backed by the linked official sources.
// The completion pass should expand and editorially review this catalog without moving it into CONFIG.
export const AROUND_YOU_SEED_PLACES: AroundYouPlace[] = [
  {
    id: "downtown-salt-lake-city",
    enabled: true,
    latitude: 40.7608,
    longitude: -111.891,
    category: "city",
    contextType: "region",
    priority: 54,
    triggerRadiusMeters: 4_500,
    discoveryRadiusMeters: 9_000,
    title: { en: "Downtown Salt Lake City", es: "Centro de Salt Lake City" },
    description: {
      en: "Utah's capital city sits between the Wasatch Mountains and the Great Salt Lake.",
      es: "La capital de Utah se encuentra entre las montañas Wasatch y el Gran Lago Salado.",
    },
    sourceUrl: "https://www.slc.gov/",
  },
  {
    id: "utah-state-capitol",
    enabled: true,
    latitude: 40.7774,
    longitude: -111.8882,
    category: "history",
    contextType: "landmark",
    priority: 96,
    triggerRadiusMeters: 1_500,
    discoveryRadiusMeters: 5_500,
    title: { en: "Utah State Capitol", es: "Capitolio del Estado de Utah" },
    description: {
      en: "The Capitol overlooks Salt Lake City from the north end of State Street.",
      es: "El Capitolio domina Salt Lake City desde el extremo norte de State Street.",
    },
    sourceUrl: "https://www.slc.gov/district3/tour-district-3/utah-state-capitol/",
  },
  {
    id: "salt-lake-city-airport",
    enabled: true,
    latitude: 40.7899,
    longitude: -111.9791,
    category: "transportation",
    contextType: "landmark",
    priority: 88,
    triggerRadiusMeters: 3_500,
    discoveryRadiusMeters: 10_000,
    title: {
      en: "Salt Lake City International Airport",
      es: "Aeropuerto Internacional de Salt Lake City",
    },
    description: {
      en: "Salt Lake City's airport is a major gateway to Utah and the Mountain West.",
      es: "El aeropuerto de Salt Lake City es una importante puerta de entrada a Utah y el oeste montañoso.",
    },
    sourceUrl: "https://slcairport.com/about-the-airport/airport-overview/",
  },
  {
    id: "great-salt-lake-state-park",
    enabled: true,
    latitude: 40.7347,
    longitude: -112.2128,
    category: "nature",
    contextType: "landmark",
    priority: 92,
    triggerRadiusMeters: 7_500,
    discoveryRadiusMeters: 18_000,
    title: { en: "Great Salt Lake", es: "Gran Lago Salado" },
    description: {
      en: "This terminal lake has no outlet; water leaves through evaporation while minerals remain.",
      es: "Este lago terminal no tiene salida; el agua se evapora mientras los minerales permanecen.",
    },
    sourceUrl: "https://stateparks.utah.gov/parks/great-salt-lake/",
  },
  {
    id: "lagoon-amusement-park",
    enabled: true,
    latitude: 40.9847,
    longitude: -111.895,
    category: "culture",
    contextType: "landmark",
    priority: 84,
    triggerRadiusMeters: 2_200,
    discoveryRadiusMeters: 7_000,
    title: { en: "Lagoon", es: "Lagoon" },
    description: {
      en: "A longtime Utah amusement park located in Farmington.",
      es: "Un histórico parque de diversiones de Utah ubicado en Farmington.",
    },
    sourceUrl: "https://www.lagoonpark.com/contact-us/",
  },
  {
    id: "ogden",
    enabled: true,
    latitude: 41.223,
    longitude: -111.9738,
    category: "history",
    contextType: "region",
    priority: 58,
    triggerRadiusMeters: 6_500,
    discoveryRadiusMeters: 13_000,
    title: { en: "Ogden", es: "Ogden" },
    description: {
      en: "Once known as Junction City, Ogden grew around its important railroad connections.",
      es: "Conocida como Junction City, Ogden creció alrededor de sus importantes conexiones ferroviarias.",
    },
    sourceUrl: "https://council.ogdencity.com/560/About-Ogden",
  },
  {
    id: "park-city",
    enabled: true,
    latitude: 40.6461,
    longitude: -111.498,
    category: "city",
    contextType: "region",
    priority: 64,
    triggerRadiusMeters: 6_000,
    discoveryRadiusMeters: 12_000,
    title: { en: "Park City", es: "Park City" },
    description: {
      en: "A historic silver-mining town that became a year-round mountain and arts destination.",
      es: "Una histórica ciudad minera de plata convertida en destino de montaña y artes durante todo el año.",
    },
    sourceUrl: "https://www.visitparkcity.com/things-to-do/museums-history/park-city-history/",
  },
  {
    id: "utah-olympic-park",
    enabled: true,
    latitude: 40.7114,
    longitude: -111.561,
    category: "sports",
    contextType: "landmark",
    priority: 95,
    triggerRadiusMeters: 2_500,
    discoveryRadiusMeters: 9_000,
    title: { en: "Utah Olympic Park", es: "Parque Olímpico de Utah" },
    description: {
      en: "A 2002 Winter Games venue that continues Utah's Olympic sport legacy.",
      es: "Una sede de los Juegos de Invierno de 2002 que continúa el legado deportivo olímpico de Utah.",
    },
    sourceUrl: "https://utaholympiclegacy.org/about/",
  },
];
